name: Build and deploy Nest.js app to Azure Web App - opmey-api-v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build Nest.js app
        run: npm run build

      - name: Zip artifact for deployment
        run: zip release.zip -r dist/* package.json package-lock.json

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: nest-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: nest-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4EB190F7A10C423B816A2E82532B07AF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D00F94FD30D3451BBDDD0832C84D6520 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_569826BEDDEE475DBCC8FD85C2B64E11 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'opmey-api-v2'
          slot-name: 'Production'
          package: ./deploy
